# Generated by Django 5.0.6 on 2024-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="paid_lesson",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="почта"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(verbose_name="пароль"),
        ),
    ]
