# Generated by Django 5.0.6 on 2024-06-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_remove_course_owner_remove_lesson_owner"),
        ("users", "0002_remove_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="курс",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="урок",
            ),
        ),
    ]
